---
title: "Adding bigfoot.js to Hugo"
author: "Junsok Huhh"
date: 2017-11-01
tags: ['bigfoot', 'js', 'Hugo']
categories: ['R', 'Hugo'] 
---

# BIGFOOT! 

웹서핑을 하다가 이 녀석을 보고야 말았다, [bigfoot.js](http://bigfootjs.com/). 웹 문서 표준들 고도화된 지금의 시점에서 인터넷을 통해 노출하는 문서에서 표현의 방법이 제약되는 경우는 거의 없다. 표, 수식, 그림 등을 동원해 소통하는 데에 pdf 보다 나은 사례도 많다. 당장 이 문서가 작성되고 있는 markdown이 대표적이다. 

개인적으로 각주 처리면 좀 더 '멋지게' 되면 좋겠는데, 싶었다. 마치 등이 살짝 가려운 데 긁지 못하는 격이랄까. 이때 `bigfoot.js`를 보게된 것이다! 각주를 누르면 버블로 해당 텍스트가 그 자리에 등장한다. 이거야말로 인터랙티브 문서가 지닌 장점이 아닌가! 

그래서 바로 검색 들어 갔다. 우선, 필요한 요소를 챙겨보자. 

  1. `bigfoot.js`를 구현하는 자바 스크립트 
  2. 해당 자바스크립트를 이 공간이 사용하고 있는 Hugo framework에 배치하기 
  
이 두가지만 얼추 해결되면 될 듯 싶었다. 어제 밤에 딱 10분 검색해서 찾아냈다.[^first]

[^first]: 부끄럽지만 몹시 뿌듯하고 기뻤다! ㅎ 

# How to install[^source]

[^source]: 이 내용의 출처는 [여기](http://egeiro.net/post/barefoot-notes/)다. 

원래 `bigfoot.js`는 큰 점 세계가 나오는 형태여서 숫자로 표기되는 전통적인 각주와는 어울리지 않는다. `bigfoot.js`는 보다 간략한 형태의 `barefoot.min.js`도 제공한다. 이 녀석을 붙여보기로 하자. 

  1. [barefoot github](https://github.com/philgruneich/barefoot)에서 `barefoot.min.js`, `barefoot.min.css`를 다운 받는다. 
  2. `barefoot.min.js`을 `static/js`에 넣어준다. 혹시 `static` 디렉토리 안에 `js`가 없다면 만들면 된다. 
  3. `barefoot.min.css`을 `static/css`에 넣어준다. 
  4. `themes/[YOUR_THEME_NAME]//layouts/partials/footer.html`을 열어서 아래 코드를 적절한 위치에 삽입한다. 
  
```{}
<link rel="stylesheet" href="/css/barefoot.min.css">

<script src="/js/barefoot.min.js"></script>
<script>
  lf = new BareFoot();
  lf.init();
</script>
```

# How to use 

그냥 markdown에 각주 쓰듯이 쓰면 되겠다. 

```{}
This is barefoot![^baref]

[^baref]: 이것은 베어풋으로 붙인 각주입니다! 
```

This is barefoot![^baref]

[^baref]: 이것은 베어풋으로 붙인 각주입니다! 