---
title: "All dots are not created same..." 
author: "Junsok Huhh"
date: 2017-10-18
tags: ['LaTeX']
categories: ['typesetting', 'math_symbol', 'ams']

---

# `\cdots`, `\ldots`, and so on

$\mathrm \LaTeX$으로 조판하는 분들에게는 가끔 이건 뭐지, 싶은 사항들이 몇 개 있다. 요즘은 무늬로나마 공부하는 사람일 때 만큼 $\mathrm \LaTeX$을 쓰지 않는다. 그래도 가끔 쓰긴 쓰기에, 오히려 이런 지엽적인 궁금한 내용에 관심을 쏟기도 한다. 

문득, 뭔가를 쓰다가 `\cdots`($\cdots$)과 `\ldots`($\ldots$)은 어떻게 다르지, 라는 데 생각이 미쳤다. 분명, 수학 기호의 일부이기 때문에 다르기는 다를텐데 말이다. 역시 달랐다! 천조국 수학회(AMS)에서 관리하는 기호 패키지인 `amsmath` 패키지의 [이용자 매뉴얼](http://www.tug.org/teTeX/tetex-texmfdist/doc/latex/amsmath/amsldoc.pdf)에 따르면 이들 사이에 분명하게 명령어 차원에서 구분되어 있다. 이 매뉴얼은 현재 2.0 버전이 최신 버전이고, 이게 만들어진 것이 2002년 2월 25일이다... (그간 이 매뉴얼을 볼 생각을 하지 않았다니 ㅠㅠ)

# According to AMS package guide 

가이드 12쪽에 보면 이렇게 다섯가지로 구분되어 있다. 

  1. `\dotsc` for "dots with commas"
  2. `\dotsb` for "dots with binary operators / relations"
  3. `\dotsm` for "multiplication dots"
  4. `\dotsi` for "dots with integrals"
  5. `\dotso` for "other dots" (none of the above)
  
AMS 구분을 보고 무릎을 '탁' 쳤다. 바로 이것이다! 

실제로 써보자. 

  1. `\dotsc`: $A_1, A_2, \dotsc$
  2. `\dotsb`: $A_1 + A_2 + \dotsb$ 
  3. `\dotsm`: $A_1 A_2 \dotsm$
  4. `\dotsi`: $\begin{aligned}
                 \int_{A_1} \int_{A_2} \dotsi 
                 \end{aligned}$
  
뭐 다 비슷비슷해 보일 수 있으나, 참으로 감동이 아닌가! 
