---
output: 
  html_document: 
    css: styles_cv.css
# pdf_document:
#  latex_engine: pdflatex
#  template: ~/Dropbox/miscelanea/svm-r-markdown-templates/svm-latex-cv.tex
# geometry: margin=1in

title: "Jun Sok Huhh"

# #jobtitle: "Chief Brewer, Arthur Guinness & Son"
# #address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
# fontawesome: yes
# email: guinness@consumer-care.net
# # github: svmiller
# phone: "+353 1 408 4800"
# web: guinness.com
# updated: no
# 
# keywords: R Markdown, academic CV, template
# 
# fontfamily: mathpazo
# fontfamilyoptions: sc, osf
# fontsize: 11pt
# linkcolor: blue
# urlcolor: blue
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

*****
<div id = "vtight"> 
Team Leader, R&I Team </br>
12 Daewangpangyo-ro 644beon-gil $\cdot$ NCSOFT $\cdot$ Seongnam Gyeonggi, South Korea 13494 </br>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<i class="fa fa-envelope-o" aria-hidden="true"></i> [work](mailto: junsokhuhh@ncsoft.com) 
<i class="fa fa-envelope-o" aria-hidden="true"></i> [personal](mailto: anarinsk@gmail.com) 
<i class="fa fa-github" aria-hidden="true"></i> [personal](https://github.com/anarinsk) 
<i class="fa fa-home" aria-hidden="true"></i> [personal](http://lostineconomics.com) 
| updated: November 18, 2017 </br>
</div>

******


# Employment

*NCSOFT*, Team Leader (Seongnam Gyeonggi $\cdot$ South Korea) 2014--present 

*KISDI*, Senior Researcher (Jinchun Chungchungbuk $\cdot$ South Korea) 2013--2014 

*FourThirtyThree*, Data Anlysist (Seoul $\cdot$ South Korea) 2012--2013

*Seoul National University*, Postdoc. School of Economics (Seoul $\cdot$ South Korea) 2011--2012

# Education

*Seoul National University*, Ph.D. School of Economics 2010

*Seoul National University*, M.A. School of Economics 1997 

*Seoul National University*, B.A. School of Economics 1995

# Publications

## Books and Book Chapters 

Jun Sok Huhh. 2013. "Who’s Afraid of Social Games (Chapter 7)." *Game Phobia* [Korean language]. Communication Books. [Korean language]

Jun Sok Huhh. 2009. "The Evolution of PC bang Culture in Korea (Chapter 7)." *Gaming Cultures and Place in Asia-Pacific* [edited by Larissa Hjorth, Dean Chan]. Routledge.

Jun Sok Huhh, Larissa Hjorth and Bora Na. 2009. "Games of gender: a case study on females who play games in the Seoul, South Korea (Chapter 14)." *Gaming Cultures and Place in Asia-Pacific* [edited by Larissa Hjorth, Dean Chan]. Routledge.

Jun Sok Huhh. 2006. *Business of Fun–Economics of computer games industry*. ChekSeSang. [Korean language]

## Journal Articles

Jun Sok Huhh and Jeong Wook Byun. 2017. "North Korea’s Nuclear Weapon Development and South Korea’s Strategic Reaction: A Signaling Game Approach." *Ehwa Journal of Social Sciences* 33(1): 107--142 [Korean language]

Jun Sok Huhh and Jeong Wook Byun. 2014. "Hyperbolic Discounting and the Effect of Handset Subsidy Regulation in Mobile Telephony Service Market." *Telecommunucations Review* 24(4):566--576. [Korean language]

Jun Sok Huhh and Jeong Wook Byun. 2013. "Price Competition and Handset Subsidy Competition in Mobile Telephony Service Market." *Telecommunucations Review* 23(5):676--685. [Korean language]

Jun Sok Huhh and Jung-Kyu Choi. 2012. "The Decay in Contributions in a Public Goods Game: Learning Hypothesis, Strategy Hypothesis and Reciprocity Hypothesis Revisited." *Journal of Econometric Theory and Econometrics* 23(2):165--186. [Korean language]

Jun Sok Huhh. 2008. "Culture and Business of PC Bangs in Korea." *Games and Culture* 3(1):26--37.

Jun Sok Huhh and Sang-Woo Park. 2005. "The Emergence and Economic Functioning of Secondary Market in MMORPG." *Journal of Information Science* 23(6):42–49. [Korean language]

Jun Sok Huhh. 1999. "Finding the Alternative in-between Market and Capitalism: Theoretical Challenge of Radical Economics." *Economy and Society* 42. [Korean language]

Jun Sok Huhh. 1998. "On Theoretical Foundation of New Institutionalist Economics : ‘Power’ vs, ‘Efficiency’." *Review of Social Economics* 11. [Korean language]

Jun Sok Huhh and Jung-Kyu Choi. 1998. "Review of Radical Institutionalist economics." *Trend and Perspective* 37. [Korean language]

## Technical Skills 

### Proficient
R, Mathematica, $\rm \LaTeX$

### Familiar
Python, NetLogo, Docker